-- 10 additional sample cafes with real coordinates for map testing
INSERT INTO items (slug, name, description, content, category, city, state, latitude, longitude, source_url) VALUES
('signal-coffee', 'Signal Coffee', 'Minimalist cafe with lightning-fast fiber internet and standing desks.', 'Signal Coffee is a dream for remote workers who need reliable, blazing-fast internet. Located in downtown Austin, this minimalist space features standing desks, noise-canceling pods, and a curated menu of single-origin pour-overs. The fiber connection consistently tests at 500+ Mbps.', 'Fast WiFi', 'Austin', 'TX', 30.2672, -97.7431, 'https://example.com/signal-coffee'),

('hush-house', 'Hush House', 'A library-quiet cafe with a strict no-phone-calls policy.', 'Hush House takes the quiet cafe concept to the next level with a strict no-phone-calls policy and sound-absorbing panels on every wall. Located in Portland''s Pearl District, it''s the go-to spot for writers, coders, and anyone who needs deep focus. The cold brew is outstanding.', 'Quiet & Focused', 'Portland', 'OR', 45.5231, -122.6765, 'https://example.com/hush-house'),

('rooftop-grind', 'Rooftop Grind', 'Open-air rooftop cafe with city skyline views and strong WiFi.', 'Perched atop a converted warehouse in Brooklyn, Rooftop Grind offers panoramic views of the Manhattan skyline alongside excellent espresso. The covered section has heaters for cooler months, and the WiFi reaches every corner of the terrace. Popular with freelance designers and photographers.', 'Outdoor', 'Brooklyn', 'NY', 40.6782, -73.9442, 'https://example.com/rooftop-grind'),

('midnight-drip', 'Midnight Drip', '24-hour cafe catering to night owls and deadline warriors.', 'Midnight Drip never closes. This Chicago institution has been fueling late-night coding sessions and last-minute presentations since 2018. The vibe shifts throughout the day — bustling in the morning, mellow in the afternoon, and electric after midnight when the real regulars show up.', 'Late Night', 'Chicago', 'IL', 41.8827, -87.6233, 'https://example.com/midnight-drip'),

('golden-gate-grind', 'Golden Gate Grind', 'Sunny Mission District cafe with an outdoor parklet and craft lattes.', 'Golden Gate Grind transformed a parking spot into the neighborhood''s favorite parklet. Located on Valencia Street in San Francisco''s Mission District, it serves craft lattes and has a relaxed, social atmosphere. The indoor space has communal tables perfect for casual co-working.', 'Social & Buzzy', 'San Francisco', 'CA', 37.7599, -122.4148, 'https://example.com/golden-gate-grind'),

('front-porch-coffee', 'Front Porch Coffee', 'Southern charm meets fast WiFi in a wraparound porch setting.', 'Front Porch Coffee lives up to its name with a beautiful wraparound porch overlooking one of Savannah''s iconic squares. Inside, you''ll find fast WiFi, plenty of outlets, and some of the best peach iced tea in Georgia. The slow Southern pace makes it ideal for deep work.', 'Outdoor', 'Savannah', 'GA', 32.0809, -81.0912, 'https://example.com/front-porch-coffee'),

('alpine-espresso', 'Alpine Espresso', 'Mountain-town cafe with panoramic Rocky Mountain views.', 'Alpine Espresso sits at 5,280 feet with floor-to-ceiling windows framing the Rocky Mountains. This Denver favorite attracts remote workers who want inspiration with their americano. The space is airy and modern, with fast WiFi and a no-meeting-calls zone upstairs.', 'Quiet & Focused', 'Denver', 'CO', 39.7392, -104.9903, 'https://example.com/alpine-espresso'),

('neon-bean', 'Neon Bean', 'Retro-themed late-night cafe with neon signs and vinyl records.', 'Neon Bean is Nashville''s most Instagram-worthy cafe, decked out in vintage neon signs and a curated vinyl collection that plays through warm tube amplifiers. Open until 2 AM on weekends, it draws musicians, songwriters, and creative types. The espresso martini is legendary.', 'Late Night', 'Nashville', 'TN', 36.1627, -86.7816, 'https://example.com/neon-bean'),

('tide-pool-cafe', 'Tide Pool Cafe', 'Beachside cafe with ocean views and a laid-back surf vibe.', 'Tide Pool Cafe sits steps from the beach in Santa Monica, offering ocean views from every seat. The vibe is pure California — laid-back, sunny, and welcoming. Surfers, freelancers, and tourists share the communal tables. WiFi is solid and the acai bowls are a must-try.', 'Outdoor', 'Santa Monica', 'CA', 34.0195, -118.4912, 'https://example.com/tide-pool-cafe'),

('the-compiler', 'The Compiler', 'Developer-themed cafe with mechanical keyboards you can borrow.', 'The Compiler is a love letter to software culture. This Seattle cafe offers loaner mechanical keyboards, USB-C charging at every seat, and a menu where drinks are named after programming languages. The "Java" is predictably their best seller. Pair programming encouraged.', 'Fast WiFi', 'Seattle', 'WA', 47.6062, -122.3321, 'https://example.com/the-compiler');
