-- Seed: 15 work-friendly cafes across 5 categories
DELETE FROM items;

INSERT INTO items (slug, name, description, content, category, city, state, source_url, featured, created_at) VALUES
('byte-and-brew', 'Byte & Brew', 'Lightning-fast internet and bottomless drip coffee. The dev favorite.', 'Byte & Brew was founded by two ex-engineers who got tired of hunting for reliable WiFi. The result: a cafe purpose-built for deep work. Every seat has a power outlet within arm''s reach, the internet is symmetric gigabit, and the drip coffee is always fresh. They even have a "focus mode" hour from 9-10am where music drops to ambient only.', 'Fast WiFi', 'Austin', 'TX', 'https://example.com/byte-and-brew', 1, datetime('now')),

('the-quiet-type', 'The Quiet Type', 'Library-meets-cafe energy. No phone calls allowed.', 'Walking into The Quiet Type feels like entering a reading room that happens to serve excellent coffee. Strict no-call policy, soft lighting, and a curated playlist that never rises above a murmur. Writers, researchers, and anyone who needs uninterrupted focus swear by this place. Their lavender latte is legendary.', 'Quiet & Focused', 'Portland', 'OR', 'https://example.com/quiet-type', 1, datetime('now')),

('nomads-landing', 'Nomad''s Landing', 'Built by remote workers, for remote workers. Standing desks and all.', 'Nomad''s Landing was designed from scratch around the needs of digital nomads. Standing desks, booking-free meeting pods, a timezone clock wall, and a community Slack channel. The food menu rotates globally — tacos on Tuesday, pho on Thursday. Monthly memberships come with mail forwarding.', 'Fast WiFi', 'Denver', 'CO', 'https://example.com/nomads-landing', 1, datetime('now')),

('basecamp-coffee', 'Basecamp Coffee', 'Where startup founders bump into each other accidentally-on-purpose.', 'Part cafe, part incubator energy. Basecamp Coffee attracts a crowd of founders, freelancers, and investors. The communal tables are big and the conversations are bigger. They host weekly "office hours" where local mentors drop in. The espresso is serious — single-origin, rotated monthly.', 'Social & Buzzy', 'San Francisco', 'CA', 'https://example.com/basecamp-coffee', 1, datetime('now')),

('the-late-grind', 'The Late Grind', 'Open until midnight. Your second office after dark.', 'Not everyone works 9-to-5. The Late Grind stays open until midnight every night, serving anyone who does their best thinking after sunset. Warm lighting, strong WiFi, and a kitchen that serves real food (not just pastries) until 11pm. Popular with grad students, night-owl freelancers, and anyone avoiding their apartment.', 'Late Night', 'Chicago', 'IL', 'https://example.com/late-grind', 0, datetime('now')),

('patio-protocol', 'Patio Protocol', 'Shaded garden, strong WiFi, and stronger espresso.', 'A sprawling outdoor workspace tucked behind a vine-covered wall. Patio Protocol proves you don''t need to be indoors to be productive. The garden has weatherproof power outlets, mesh WiFi that reaches every table, and enough shade to kill screen glare. Their cold brew is brewed for 24 hours.', 'Outdoor', 'Savannah', 'GA', 'https://example.com/patio-protocol', 0, datetime('now')),

('draft-and-deploy', 'Draft & Deploy', 'Named after git, not beer. Though they have both.', 'The nerdiest cafe in the best way. Draft & Deploy has terminal-themed menus, rubber duck debugging companions at every table, and a "deploy Friday" happy hour. But beneath the theme, it''s genuinely great — fast internet, ergonomic chairs, and baristas who understand "just keep the coffee coming."', 'Fast WiFi', 'Seattle', 'WA', 'https://example.com/draft-deploy', 0, datetime('now')),

('murmur-cafe', 'Murmur Cafe', 'Ambient noise perfectly calibrated for flow state.', 'The owners of Murmur studied the research: moderate ambient noise boosts creative thinking. So they engineered their space around it. The background hum is just right — not silent, not loud. Acoustic panels, a no-blender policy during peak hours, and specialty pour-overs that arrive without interrupting your train of thought.', 'Quiet & Focused', 'Nashville', 'TN', 'https://example.com/murmur-cafe', 0, datetime('now')),

('common-ground', 'Common Ground', 'Big communal tables and a whiteboard wall. Ideas happen here.', 'If you need to brainstorm, Common Ground is your spot. Massive tables designed for spreading out, a full whiteboard wall anyone can use, and a vibe that encourages striking up conversation with strangers. Their "collab corner" has a big screen you can AirPlay to. Great for small team offsites.', 'Social & Buzzy', 'Brooklyn', 'NY', 'https://example.com/common-ground', 0, datetime('now')),

('the-daily-standup', 'The Daily Stand-Up', 'Private booths and fast video calls. Great for meetings.', 'Named after the morning ritual every remote team knows. The Daily Stand-Up has four soundproof phone booths, studio-quality lighting for video calls, and a "meeting mode" WiFi tier with guaranteed bandwidth. Book a booth through their app or just grab a table. The breakfast burritos fuel many a sprint planning session.', 'Fast WiFi', 'Austin', 'TX', 'https://example.com/daily-standup', 0, datetime('now')),

('analog-coffee', 'Analog Coffee', 'No screens on the menu. Just good beans and good focus.', 'A deliberate throwback. Analog Coffee encourages — but doesn''t enforce — analog work. Journals and sketchbooks line the shelves for borrowing, the tables are solid wood, and the WiFi password is only given on request. Popular with designers and writers who want to unplug from notifications while staying caffeinated.', 'Quiet & Focused', 'Asheville', 'NC', 'https://example.com/analog-coffee', 0, datetime('now')),

('greenhouse-workspace', 'Greenhouse Workspace', 'Plants everywhere. Natural light therapy disguised as a cafe.', 'Half botanical garden, half workspace. Greenhouse has floor-to-ceiling windows, hanging plants above every table, and a living wall that doubles as a room divider. The natural light is genuinely mood-boosting. They serve matcha and golden milk alongside traditional coffee, and every purchase plants a tree.', 'Outdoor', 'Los Angeles', 'CA', 'https://example.com/greenhouse-workspace', 0, datetime('now')),

('red-eye-roasters', 'Red Eye Roasters', 'Triple shots and 2am deadlines. They get it.', 'Red Eye is for the all-nighters. Open 24/7 on weekdays, they cater to deadline-driven workers with strong coffee and zero judgment. The space is split into "active" and "quiet" zones, and they offer a "midnight menu" of comfort food. Their namesake Red Eye — espresso + drip — is not for the faint of heart.', 'Late Night', 'New York', 'NY', 'https://example.com/red-eye-roasters', 0, datetime('now')),

('the-async-lounge', 'The Async Lounge', 'Work at your own pace. No rush, ever.', 'The Async Lounge has no closing announcements, no side-eyes for nursing one coffee for three hours, and no pressure to buy more. They operate on a time-based model — pay by the hour, coffee included. Deep couches, private nooks, and the most patient staff in the city. Designed for marathon work sessions.', 'Quiet & Focused', 'Minneapolis', 'MN', 'https://example.com/async-lounge', 0, datetime('now')),

('merge-cafe', 'Merge Cafe', 'Coworking meets coffee shop. Day passes available.', 'Merge blurs the line between cafe and coworking space. Buy a day pass and get a dedicated desk, monitor, and unlimited coffee. Or just grab a table in the open area. They host "Demo Day" every month where members show what they''ve been building. The community alone is worth the visit.', 'Social & Buzzy', 'Miami', 'FL', 'https://example.com/merge-cafe', 0, datetime('now'));
